spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: dev
#开启服务降级
feign:
  hystrix:
    enabled: true
#Eureka配置，服务注册到哪里
eureka:
  client:
    register-with-eureka: false  #不向Eureka注册自己
    service-url:
      defaultZone: http://zty1.com:7001/eureka/,http://zty2.com:7002/eureka,http://zty3.com:7003/eureka
---
server:
  port: 8081
spring:
  profiles: sit
#开启服务降级
feign:
  hystrix:
    enabled: true
#Eureka配置，服务注册到哪里
eureka:
  client:
    register-with-eureka: false  #不向Eureka注册自己
    service-url:
      defaultZone: http://zty1.com:7001/eureka/,http://zty2.com:7002/eureka,http://zty3.com:7003/eureka
---
server:
  port: 8081
spring:
  profiles: prod
#开启服务降级
feign:
  hystrix:
    enabled: true
#Eureka配置，服务注册到哪里
eureka:
  client:
    register-with-eureka: false  #不向Eureka注册自己
    service-url:
      defaultZone: http://zty1.com:7001/eureka/,http://zty2.com:7002/eureka,http://zty3.com:7003/eureka
